### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by limed**

### CODE REVIEW

**Comment by gozer** [comment]
If that option now defaults properly, great! But I would also mention the minimum version of vault required in the docs so it doesn't bite people running older versions

**Comment by limed** [comment]
> If that option now defaults properly, great! But I would also mention the minimum version of vault required in the docs so it doesn't bite people running older versions 

I believe the default is to encrypt to a file locally, the tip of master for aws-vault has this fixed. During the training session there was some confusion on the `--backend=kwallet` for mac folks so I put a note in that that says "linux users use --backed=kwallet"

**Comment by gozer** [comment]
Understood. Why not make it even simpler for Linux folks and point them at:

``` bash
export AWS_VAULT_BACKEND=kwallet
```

**Comment by tinnightcap** [comment]
Actually the export AWS_VAULT_BACKEND=kwallet bit is already in there with an explanation a few lines up. I simply forgot to remove the option from a few commands.

@limed can you simply remove the comment you added about linux users? That should fix this right up.

**Review by tinnightcap — APPROVED** [review]
Looks good.

r+

**Pull request merged**
